client_id = "a94fb70b5b04fc8e18e80b1663eae59a"
name = "CartGuard"
application_url = "https://cartguard-co1f.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-shop-qay2qcgj.myshopify.com"

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
  "https://cartguard-co1f.onrender.com/auth/callback",
  "https://cartguard-co1f.onrender.com/auth/shopify/callback",
  "https://cartguard-co1f.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://cartguard-co1f.onrender.com/webhooks"
  customer_deletion_url = "https://cartguard-co1f.onrender.com/webhooks"
  shop_deletion_url = "https://cartguard-co1f.onrender.com/webhooks"

[pos]
embedded = false
