query RunInput($limitTags: [String!] = []) {
  cart {
    buyerIdentity {
      email
      customer {
        email
      }
    }
    lines {
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            hasTags(tags: $limitTags) {
              tag
              hasTag
            }
          }
        }
      }
    }
    deliveryGroups {
      deliveryAddress {
        address1
        address2
        city
        provinceCode
        zip
        countryCode
      }
    }
  }
  cost {
    totalAmount {
      amount
      currencyCode
    }
  }
  shop {
    settings: metafield(namespace: "$app:cartguard", key: "settings") { value }
    regex_rules: metafield(namespace: "$app:cartguard", key: "regex_rules") { value }
    quantity_limits: metafield(namespace: "$app:cartguard", key: "quantity_limits") { value }
    geo_blocklist: metafield(namespace: "$app:cartguard", key: "geo_blocklist") { value }
    vip_allowlist: metafield(namespace: "$app:cartguard", key: "vip_allowlist") { value }
  }
}
