api_version = "2026-07"

[[extensions]]
name = "CartGuard Validator"
handle = "cartguard-validator"
type = "function"

  [[extensions.targeting]]
  target = "purchase.validation.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  typegen_command = "echo 'GraphQL types up to date'"
  path = "dist/index.wasm"

  [[extensions.metafields]]
  namespace = "cartguard"
  key = "regex_rules"

  [[extensions.metafields]]
  namespace = "cartguard"
  key = "quantity_limits"

  [[extensions.metafields]]
  namespace = "cartguard"
  key = "geo_blocklist"

  [[extensions.metafields]]
  namespace = "cartguard"
  key = "vip_allowlist"

  [[extensions.metafields]]
  namespace = "cartguard"
  key = "settings"
